Fix npm audit vulnerabilities
authgear/authgear-sdk-js pull request #29
Opened 2020-10-22 15:43 UTC by axolotl0212

fix #27 
fix #7 
fix #12

2020-10-22 15:48 UTC, axolotl0212 commented
merging #8 and #9 should fix some of the vulnerabilities in `/website`

2020-10-23 02:22 UTC, louischan-oursky requested changes

2020-10-23 02:22 UTC, louischan-oursky commented on package.json
> +    "@babel/cli": "^7.12.1",
Let's bump babel to latest versions. And please remember we use exact version.

2020-10-23 03:13 UTC, axolotl0212 commented
@louischan-oursky updated

2020-11-04 03:22 UTC, merged