List all user info attributes in examples
authgear/authgear-sdk-js pull request #291
Opened 2024-05-16 08:06 UTC by randy1yu

ref #252 
ref DEV-1029

2024-05-17 03:22 UTC, louischan-oursky commented on example/reactnative/src/screens/MainScreen.tsx
> +        `id: ${userInfo.sub}`,
I think we can simply write this. Note we use `raw` here.

```javascript
Alert.alert(
  'User Info',
  JSON.stringify(userInfo.raw, null, 2)
)
```

2024-05-20 03:51 UTC, louischan-oursky requested changes
- Please also change example/reactweb/src/App.tsx#494 to use userInfo.raw
- Please also change example/capacitor/src/pages/Home.tsx#167 to use userInfo.raw

2024-05-20 06:39 UTC, randy1yu commented
Updated

2024-05-20 10:42 UTC, louischan-oursky approved these changes

2024-05-20 10:42 UTC, merged